name:                vsynth
version:             0.1.0.0
github:              "githubuser/vsynth"
license:             BSD3
author:              "Tobias Theus, Carolina Gerhardt"
maintainer:          "example@example.com"
copyright:           "Karrot. ALLES NUR ICH. ICH ALLEINE. CREDIT NUR AN MIR."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vsynth#readme>

dependencies:
- base >= 4.7 && < 5
- OpenAL >= 1.7.0.5
- bytestring >= 0.10.10.0
- process >= 1.6.8.0
- ALUT >= 2.4.0.3
- WAVE >= 0.1.6
- split >= 0.2.3.4
- random >= 1.1
- lens >= 4.18.1
- gtk3 >= 0.15.5
- text >= 1.2.4.0
- text-conversions >= 0.3.0
- directory
- glib
- mtl >= 2.2.2
- MonadRandom >= 0.5.2
- async >= 2.2.2
- concurrency >= 1.11.0.0
- monad-par >= 0.3.5
- deepseq >= 1.4.4.0

library:
  source-dirs: src

executables:
  vsynth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vsynth

tests:
  vsynth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vsynth
